/* Original simulated Trading & Options lessons. No market feed or trade execution. */
'use strict';
const QuantApplied=(()=>{
 const definitions=[
  ['market-contracts','Read an option chain',['arith-fraction'],'Read the option type, strike, expiry, quote side and explicit contract multiplier.',
   'A call grants a right to buy; a put grants a right to sell at its strike under the contract terms. A chain groups contracts by expiry and strike. Premium quotes are per underlying unit; multiply by the stated contract multiplier and number of contracts. A buyer crosses to the ask and a seller to the bid under our immediate-fill assumption.',
   'SIMULATED: a put row shows strike 95, expiry 2030-06-21, bid 1.8 / ask 2.0, multiplier 10. Buying 3 contracts costs 2.0 × 10 × 3 = 60 before fees. The strike 95 is not the option premium.',
   'Confusing strike with premium, using the midpoint as a guaranteed fill, or assuming every multiplier is 100.'],
  ['market-execution','Execution and transaction costs',['market-contracts','arith-percent'],'Calculate signed opening and closing cash flows with bid/ask and per-contract fees.',
   'Buying costs ask × multiplier × quantity plus fees. Selling receives bid × multiplier × quantity minus fees. Round-trip profit is cash received minus cash paid, regardless of which happens first. Our simulated fills assume sufficient size and no slippage beyond the stated spread; a real quote is not a fill guarantee.',
   'SIMULATED: bid 3 / ask 3.2, multiplier 10, 2 contracts, fee 0.5 per contract per side. Buy outflow = 65; unchanged-quote sale proceeds = 59; profit = -6. Midpoint 3.1 does not remove the spread.',
   'Using the same quote side twice, forgetting one set of fees, or multiplying per-contract fees by the underlying multiplier.'],
  ['market-options','Expiry payoff versus profit',['market-execution'],'Separate moneyness, expiry payoff, net profit and fee-adjusted breakeven for long calls and puts.',
   'At expiry a call pays max(spot − strike, 0) per unit; a put pays max(strike − spot, 0). Multiply payoff by the stated multiplier and quantity, then subtract opening premium and fee. In the money means positive intrinsic value, not necessarily profit. We assume cash-equivalent expiry payoff, no additional settlement fee, and no early exercise, financing or dividends.',
   'SIMULATED long call: strike 50, premium 3, multiplier 10, one contract, opening fee 1. At expiry spot 52, payoff is 20 but initial cost is 31: net profit -11 despite being in the money. Breakeven is 50 + 3 + 1/10 = 53.1.',
   'Reporting intrinsic value as net profit or treating in-the-money as profitable.'],
  ['market-quote','Conditional value and quoting',['market-execution','prob-ev','prob-bayes'],'Condition on customer action and compare conditional value with the correct side of a quote.',
   'A customer action may convey information. First weight each value state by both its prior and the probability of that action, then normalize. A dealer selling receives price minus conditional value; a dealer buying receives conditional value minus price. The model is a one-unit, two-state simulation with no fees, inventory costs or other customers.',
   'SIMULATED: values 60 or 40, equal priors. A customer buys with probability .75 in the high state and .25 in the low state. Given a buy, high-state probability is .75 and conditional value is 55. Selling at 53 has expected profit -2, even though 53 exceeds the unconditional mean 50.',
   'Using the unconditional mean after observing an informative action or reversing dealer buy/sell profit.'],
  ['market-greeks','Greek scenario approximation',['market-options','prob-ev'],'Apply initial delta/gamma/theta/vega with consistent units and scale to the contract position.',
   'For a small scenario, approximate per-unit change as delta × spot change + 0.5 × gamma × spot change² + theta × elapsed days + vega × IV percentage-point change. Greeks are local rates, not constants valid for all scenarios. Use the quoted units: 20% to 23% is 3 volatility points. The result is an approximation, not a tradable quote or full pricing model.',
   'SIMULATED: initial value 2, delta .4, gamma .02, theta -.01/day, vega .08 per volatility point. Spot +1, IV +2 points, one day: change .4 + .01 − .01 + .16 = .56, approximate value 2.56. One contract with multiplier 10 changes by 5.6.',
   'Dropping the gamma half-factor, treating 3 volatility points as .03, changing the theta sign, or calling the approximation an executable price.']
 ];
 const skills=definitions.map(([id,name,prerequisites,objective,explanation,example,commonError])=>({id,name,prerequisites,objective,explanation,example,commonError,mode:'math',track:'applied',arcadeOnly:true,contentVersion:1,hints:['Write down the units and cash-flow direction first.','Use the stated assumptions, not a live-market convention.']}));
 const round=n=>Math.round(n*1e6)/1e6;
 function question(id,seed,harder=false,level=0){
  const skill=skills.find(s=>s.id===id);if(!skill)throw Error('Unknown applied skill');
  const v=((seed%9)+9)%9,multiplier=[100,10,50][v%3],quantity=2+v%3,premium=2+v/4,strike=105+v,fee=1+v/10;
  const q={id:`${id}:${v}:${level}`,skillId:id,seed,kind:'number',transfer:!!level,tolerance:1e-6,explanation:skill.explanation,workedExample:skill.example,hints:[],simulated:true};
  const finish=(prompt,answer,solution,construction,reason,wrong,scenario,hints)=>Object.assign(q,{prompt:'SIMULATED DATA — '+prompt,answer:round(answer),solution,construction:{prompt:construction[0],answer:round(construction[1])},correctReason:'supported',reasonOptions:[{value:'supported',label:reason},{value:'unsupported',label:wrong}],scenario,hints});
  if(id==='market-contracts'){
   const bid=4+v/10,ask=bid+.2,side=level?'sell':'buy',unit=level?bid:ask,cash=unit*multiplier*quantity;
   return finish(`A chain row for ${level?'PUT':'CALL'} XYZ, strike ${strike}, expiry 2030-06-21, shows bid ${round(bid)} / ask ${round(ask)} currency per unit; multiplier ${multiplier} units per contract. ${side==='buy'?'Buy':'Sell to open'} ${quantity} contracts. Fees are zero and immediate fill at the displayed side is assumed. What is the ${side==='buy'?'premium cash paid':'premium cash received'} in currency?`,cash,`${side==='buy'?'Ask':'Bid'} ${round(unit)} × ${multiplier} × ${quantity} = ${round(cash)} currency. Strike and premium are different fields.`,['What is the per-unit quote used for this transaction?',unit],level?'A put holder has a right to sell at the strike; a seller receives the bid premium.':'A call holder has a right to buy at the strike; a buyer pays the ask premium.','Use the strike as the premium and assume a multiplier of 100.',{side,bid,ask,multiplier,quantity},[`Identify the ${level?'put':'call'} row and its stated multiplier.`,`For ${side==='buy'?'buying use the ask':'selling use the bid'}; multiply by contract quantity and multiplier.`]);
  }
  if(id==='market-execution'){
   const bid=4+v/10,ask=bid+.2,perFee=.65+v/20,closingAsk=level?ask+(v%2?-.6:.3):ask;
   const opening=level?bid*multiplier*quantity-perFee*quantity:ask*multiplier*quantity+perFee*quantity;
   const closing=level?closingAsk*multiplier*quantity+perFee*quantity:bid*multiplier*quantity-perFee*quantity;
   const profit=level?opening-closing:closing-opening;
   return finish(`Bid ${round(bid)} / ask ${round(ask)} currency per unit; multiplier ${multiplier}; quantity ${quantity} contracts; fee ${round(perFee)} currency per contract on EACH side. ${level?`Sell to open at the bid, then buy to close when the ask is ${round(closingAsk)}.`:'Buy at the ask, then sell at the unchanged bid.'} Assume sufficient displayed size, no further slippage, financing or fees. What is net round-trip profit in currency?`,profit,`Opening ${level?'proceeds':'outflow'} ${round(opening)}; closing ${level?'outflow':'proceeds'} ${round(closing)}. Net profit ${round(profit)}.`,[`What is the opening ${level?'cash received after fees':'cash paid including fees'}?`,opening],level?'A short round trip receives the opening bid and pays the closing ask; both sides incur fees.':'A long round trip pays the opening ask and receives the closing bid; both sides incur fees.','The midpoint is a guaranteed fill, so an unchanged market has zero transaction cost.',{bid,ask,closingAsk,multiplier,quantity,perFee,short:!!level},['Separate opening and closing cash flows, with a fee on each side.','Fee is per contract, not per underlying unit. Profit is received minus paid.']);
  }
  if(id==='market-options'){
   const canonicalLoss=!level && v===1;
   const optionStrike=canonicalLoss?105:strike, optionPremium=canonicalLoss?2:premium, optionMultiplier=canonicalLoss?100:multiplier, optionFee=canonicalLoss?1:fee;
   const spot=level?optionStrike+(v%5-3):canonicalLoss?106:optionStrike+(3-v%5),units=optionMultiplier,put=!!level;
   const payoff=Math.max(put?optionStrike-spot:spot-optionStrike,0)*units,cost=optionPremium*units+optionFee,profit=payoff-cost;
   const breakeven=optionStrike+(put?-1:1)*(optionPremium+optionFee/units);
   return finish(`Long one ${put?'PUT':'CALL'}: strike ${optionStrike}, premium ${optionPremium} currency per unit, multiplier ${optionMultiplier}, opening fee ${optionFee} currency total. Expiry spot is ${spot}. Use cash-equivalent expiry payoff, no settlement fee, early exercise, financing or dividends. What is net expiry profit in currency?`,profit,`Expiry payoff = ${round(payoff)}; opening cost = ${round(cost)}; profit = ${round(profit)}. Fee-adjusted breakeven = ${round(breakeven)}. In-the-money does not guarantee profit.`,['What is the fee-adjusted expiry breakeven spot?',breakeven],put?'A long put pays max(strike − spot, 0); subtract premium and fee.':'A long call pays max(spot − strike, 0); subtract premium and fee.','Any in-the-money option must have positive net profit.',{put,strike:optionStrike,spot,premium:optionPremium,multiplier:optionMultiplier,quantity:1,fee:optionFee},[put?'A put gains intrinsic value when spot is below the strike.':'A call gains intrinsic value when spot is above the strike.','Subtract total opening cost from payoff; allocate the opening fee per unit when computing breakeven.']);
  }
  if(id==='market-quote'){
   const high=110+v*2,low=90-v,buyHigh=[.8,.7,.6][v%3],buyLow=[.2,.1,.3][v%3],sell=!!level,highLikelihood=sell?1-buyHigh:buyHigh,lowLikelihood=sell?1-buyLow:buyLow,posterior=highLikelihood/(highLikelihood+lowLikelihood),value=posterior*high+(1-posterior)*low;
   const price=round(value+(sell?-1:1)*(v%2?3:-4)),profit=sell?value-price:price-value;
   return finish(`One unit has terminal value ${high} or ${low} currency, each prior probability 1/2. Customer BUY probabilities are ${buyHigh} in the high state and ${buyLow} in the low state; SELL is the complementary action in each state. Observe a customer ${sell?'SELL':'BUY'}. You ${sell?'buy':'sell'} one unit at ${price}. Multiplier 1; fees, inventory and financing costs zero. What is your conditional expected profit in currency?`,profit,`P(high | action) = ${round(posterior)}; conditional value = ${round(posterior)} × ${high} + ${round(1-posterior)} × ${low} = ${round(value)}. Dealer profit = ${sell?'value − price':'price − value'} = ${round(profit)}.`,['What is the conditional expected terminal value after this customer action?',value],sell?'Condition on a customer sale, then dealer profit equals conditional value minus purchase price.':'Condition on a customer buy, then dealer profit equals sale price minus conditional value.','Compare the quote with the unconditional mean because the prior was symmetric.',{high,low,buyHigh,buyLow,customerSells:sell,price,multiplier:1,quantity:1},['Multiply each prior by the likelihood of the observed action and normalize.','The customer action determines which quote side the dealer takes.']);
  }
  if(id==='market-greeks'){
   const initial=4+v/10,delta=.5,gamma=.04,theta=-.03,vega=.12,spotChange=level?-(1+v%3):2+v%3,ivChange=level?-(1+v%2):3,days=2+v%2;
   const change=delta*spotChange+.5*gamma*spotChange**2+theta*days+vega*ivChange,value=initial+change;
   return finish(`Initial option value ${initial} currency/unit; delta ${delta}, gamma ${gamma}, theta ${theta} currency/unit/day, vega ${vega} currency/unit per IV percentage point. Spot change ${spotChange}; IV 20% → ${20+ivChange}%; elapsed ${days} days. Long ${quantity} contracts, multiplier ${multiplier}; fees zero. Using initial Greeks and ΔV ≈ delta·ΔS + 0.5·gamma·ΔS² + theta·days + vega·ΔIV(points), what is the approximate total POSITION value change in currency? This is a local approximation, not an executable quote.`,change*multiplier*quantity,`Per-unit changes: delta ${round(delta*spotChange)}, gamma ${round(.5*gamma*spotChange**2)}, theta ${round(theta*days)}, vega ${round(vega*ivChange)}. Sum ${round(change)}; approximate new value ${round(value)}. Position change ${round(change*multiplier*quantity)}.`,['What is the approximate NEW per-unit option value?',value],'Use initial rates with their stated units, square the signed spot move for gamma, then scale by multiplier and quantity.','The resulting approximate value is a guaranteed executable market quote.',{initial,delta,gamma,theta,vega,spotChange,ivChange,days,multiplier,quantity},[`20% to ${20+ivChange}% is ${ivChange} volatility points in the stated vega units.`,'Gamma uses half times the squared spot change; theta multiplies positive elapsed days. Sum per-unit changes before scaling the position.']);
  }
  throw Error('Unknown applied skill');
 }
 return {skills,question};
})();
if(typeof module!=='undefined')module.exports=QuantApplied;
