/* Original quant curriculum. See ATTRIBUTION.md for teaching-workflow inspiration. */
'use strict';
const QuantCurriculum = (() => {
  const skills = [
    ['arith-percent','math','arithmetic','Percentages',[], 'A percentage is a fraction of 100. Multiply the base by p / 100. Percentage changes depend on their starting base.', '10% of 80 is 8; 15% is 8 + 4 = 12.', ['Find 10% first.', 'Multiply the base by the percentage, then divide by 100.']],
    ['arith-fraction','math','arithmetic','Fractions and ratios',['arith-percent'], 'A fraction is division. To convert a fraction to a percentage, divide its numerator by its denominator and multiply by 100.', '3 / 8 = 0.375 = 37.5%.', ['Divide the numerator by the denominator.', 'Convert the decimal to a percentage by multiplying by 100.']],
    ['arith-return','math','arithmetic','Successive returns',['arith-fraction'], 'Returns compound by multiplying growth factors. A rise and an equal percentage fall do not cancel because the second change uses a different base.', '100 rising 10% becomes 110; falling 10% then leaves 99.', ['Turn each percentage into a growth factor.', 'Multiply the starting value by both factors.']],
    ['prob-complement','math','probability','Complements',[], 'An event and its complement partition all outcomes. Their probabilities sum to 1.', 'If a failure has probability 0.2, success has probability 0.8.', ['Success and failure exhaust the possibilities.', 'Subtract the given probability from 1.']],
    ['prob-conditional','math','probability','Conditional probability',['prob-complement'], 'Conditioning changes the set of possible outcomes. Count favorable outcomes within the condition, then divide by the size of that condition.', 'Among 20 selected cases, 5 succeed. The conditional success probability is 5 / 20 = 0.25.', ['Restrict the denominator to the conditioned group.', 'Divide the favorable count by that group size.']],
    ['prob-ev','math','probability','Expected value',['prob-conditional'], 'Expected value is the probability-weighted average of outcomes. It describes a long-run average, not a guaranteed individual result.', 'A fair coin pays 6 on heads and -2 on tails: EV = 0.5 × 6 + 0.5 × (-2) = 2.', ['Weight each payoff by its probability.', 'Add the weighted payoffs, including negative losses.']],
    ['brain-pigeon','brainteasers','reasoning','Worst-case guarantees',[], 'A guarantee must hold for the least favorable arrangement. Find how long that arrangement can avoid the target, then add one.', 'With three sock colors, three draws could all differ. Four draws guarantee a matching color.', ['Construct the longest sequence that avoids a match.', 'After every color has appeared once, the next draw must repeat one.']],
    ['brain-balance','brainteasers','reasoning','Information from comparisons',['brain-pigeon'], 'A balance comparison has three outcomes: left heavy, right heavy, equal. With a known heavier odd coin, balanced groups can divide the remaining candidates into three sets.', 'Among 9 coins with one known heavier, weigh 3 against 3. Each outcome leaves 3 candidates; a second weighing identifies the coin.', ['Each weighing can distinguish three outcomes.', 'Find the smallest k for which 3^k covers all candidates.']],
    ['brain-invariant','brainteasers','reasoning','Parity invariants',['brain-balance'], 'An invariant is a property an allowed operation cannot change. Removing two items preserves whether a count is odd or even.', 'Starting with 11 tokens and removing pairs can leave 1 token, but never 0.', ['Track parity rather than each possible sequence.', 'An odd count stays odd when you subtract an even count.']],
    ['brain-cases','brainteasers','reasoning','Exhaustive cases',[], 'Split outcomes into disjoint cases that cover every possibility. Add counts across disjoint cases; multiply within independent choices.', 'A two-digit code starts with 1 or 2. If it starts with 1 the last digit has 3 choices; if 2 it has 4. There are 3 + 4 = 7 codes.', ['List the disjoint cases.', 'Count within each case, then add; avoid double counting.']],
    ['brain-symmetry','brainteasers','reasoning','Symmetry',['brain-cases'], 'If equally likely outcomes are unchanged by relabeling, symmetric events have equal probabilities. Check the sampling assumption before using symmetry.', 'In a uniformly shuffled deck of 4 distinct cards, each card is equally likely to be first, with probability 1/4.', ['Which labels can be exchanged without changing the experiment?', 'Equal probabilities must sum to 1.']],
    ['brain-bounds','brainteasers','reasoning','Bounds and construction',['brain-cases'], 'First prove a lower bound, then show a construction that attains it. A lower bound alone is not a solution.', 'To seat 13 people at tables holding at most 4, at least ceil(13/4) = 4 tables are needed. Groups of 4,4,4,1 attain that bound.', ['Capacity gives a lower bound.', 'Round up total divided by capacity, then verify a feasible arrangement.']],
    ['brain-conditioning','brainteasers','reasoning','Condition on the first step',['brain-cases','prob-conditional'], 'A multistep experiment becomes simpler after conditioning on the first result. Weight each branch by its probability and add.', 'Choose a fair coin: one branch pays 4, the other pays 10. Expected payoff is (4 + 10)/2 = 7.', ['Draw the first-step branches.', 'Compute each branch result, weight it, then add.']],
    ['prob-independent','math','probability','Independent events',['prob-conditional'], 'Independence means one event does not change the probability of the other. Only under that assumption may joint probability be computed by multiplying marginal probabilities.', 'Two independent successes with probabilities 0.5 and 0.2 occur together with probability 0.1.', ['Check whether independence is explicitly given.', 'For independent events multiply their probabilities.']],
    ['prob-bayes','math','probability','Base rates and Bayes',['prob-independent'], 'A positive signal can come from a true event or a false alarm. Use base rates to count both sources before conditioning on a positive signal.', 'Among 100 cases, 10 are true. A signal catches 8 true cases and flags 9 false cases. Given a signal, probability of truth is 8/17, not 80%.', ['Count true-positive and false-positive cases.', 'Divide true positives by all positives.']],
    ['prob-variance','math','probability','Dispersion and variance',['prob-ev'], 'Variance is expected squared deviation from the mean. It measures dispersion in squared units; it does not measure the direction of the mean.', 'An equal chance of 1 or 5 has mean 3 and variance ((1-3)^2 + (5-3)^2)/2 = 4.', ['Find the mean first.', 'Average squared deviations, with probability weights.']],
    ['code-simulation','python','coding','Simulation estimates',['code-ev','prob-independent'], 'A Monte Carlo estimate averages an indicator over simulated draws. It approximates a probability; changing the sample can change the estimate. Fixed supplied draws make tests reproducible.', 'For draws [0.1, 0.6, 0.8, 0.3], the fraction below 0.5 is 2/4 = 0.5. Python: sum(x < threshold for x in draws) / len(draws).', ['Count draws satisfying the event.', 'Divide by the number of draws; round to 6 decimals.']],
    ['code-pnl','python','coding','Position P&L',[], 'For a signed position, P&L equals quantity × (exit price - entry price). A negative quantity represents a short position.', 'A position of -3 entered at 12 and exited at 10 earns (-3) × (10 - 12) = 6. Python: return quantity * (exit_price - entry_price).', ['Compute the price change first.', 'Multiply by the signed quantity.']],
    ['code-ev','python','coding','Weighted expected value',['code-pnl','prob-ev'], 'Expected value sums each outcome multiplied by its probability. Keep outcomes and probabilities paired; probabilities sum to 1.', 'For outcomes [2, 8] and probabilities [0.75, 0.25], EV = 3.5. Python pairs values with zip(outcomes, probabilities).', ['Use zip to pair outcomes and probabilities.', 'Sum value * probability for each pair; round to 6 decimals.']],
    ['code-variance','python','coding','Variance',['code-ev','prob-variance'], 'Population variance is the average squared distance from the mean. Squaring prevents positive and negative deviations from cancelling.', 'For [1, 3], the mean is 2 and variance is ((1-2)^2 + (3-2)^2)/2 = 1. Use ** 2 for a square in Python.', ['Compute the mean first.', 'Average squared deviations; divide by n, not n - 1.']],
    ['code-call','python','coding','Option payoff and profit',['code-pnl','prob-ev'], 'At expiry a long call pays max(spot - strike, 0). Profit subtracts the premium paid. These are expiry values, not a pricing model.', 'Spot 115, strike 100, premium 6: payoff 15, profit 9. At spot 90, profit is -6.', ['Separate payoff from profit.', 'Use max(spot - strike, 0) - premium.']]
  ].map(([id,mode,track,name,prerequisites,explanation,example,hints]) => ({id,mode,track,name,prerequisites,explanation,example,hints}));
  const get = id => skills.find(s => s.id === id);
  function buildQuestion(id, seed, harder = false, level = 0) {
    const s = get(id); if (!s) throw Error('Unknown skill');
    const n = (seed % 9) + 2 + (harder ? 5 : 0);
    const q = { id: `${id}:${seed % 9}:${harder ? 1 : 0}:${level}`, skillId:id, seed, transfer:level > 0, prompt:'', hints:s.hints, explanation:s.explanation, workedExample:s.example, tolerance:0.000001 };
    const numeric = (prompt,answer,solution) => Object.assign(q,{kind:'number',prompt,answer,solution});
    if(level && !id.startsWith('code-')) {
      switch(id) {
        case 'arith-percent': return numeric(`A price rises by 20% and is now ${n*12}. What was its original price?`,n*10, `Divide the final price by 1.2: ${n*12}/1.2 = ${n*10}.`);
        case 'arith-fraction': return numeric(`A fund has cash and equities in the ratio 2:3. Of a total ${n*50}, how much is cash?`,n*20, `Cash is 2/(2+3) of the total: ${n*20}.`);
        case 'arith-return': return numeric('After losing 20%, what percentage gain restores the original value? Enter the number without %. ',25,'A value of 100 falls to 80. Regaining 20 on a base of 80 requires 20/80 = 25%.');
        case 'prob-complement': return numeric(`Probabilities of three mutually exclusive exhaustive outcomes are 1/4, 1/2, and p. What is p?`,.25,'The three probabilities sum to 1: p = 1 - 1/4 - 1/2 = 1/4.');
        case 'prob-conditional': return numeric('A fair six-sided die is rolled. Given that the result is even, what is the probability it exceeds 3?',2/3,'The conditioned set is {2,4,6}; two of its three outcomes exceed 3.');
        case 'prob-ev': return numeric(`A fair coin game pays ${n*3} on heads and ${n} on tails. What entry fee makes expected net profit zero?`,n*2,`The fair fee is expected gross payoff: (${n*3}+${n})/2 = ${n*2}.`);
        case 'brain-pigeon': return numeric(`For ${n} colors, how many draws guarantee THREE socks of one color? Unlimited socks of each color are available.`,2*n+1,`At most two of each color avoids a triple: ${2*n} socks. One more forces a triple.`);
        case 'brain-balance': {const k=seed%3+2;return numeric(`A balance gives three outcomes per weighing. With ${k} weighings, at most how many candidate positions can be distinguished for a coin known to be heavier?`,3**k,`A decision tree has at most 3^${k} = ${3**k} leaves. Equal three-way partitions attain the bound.`);}
        case 'brain-invariant': return numeric(`Start with ${n*3+2} tokens and remove exactly 3 each time. What is the smallest possible remainder?`,2,`Removing 3 preserves the remainder modulo 3. ${n*3+2} leaves remainder 2.`);
      }
    }
    switch(id) {
      case 'brain-cases': return numeric(level ? `A code has two digits from 1 to ${n}. Repetition is allowed. How many codes have at least one digit equal to 1?` : `A shop offers ${n} red designs and ${n+2} blue designs, all distinct. How many ways can you choose one design?`, level ? 2*n-1 : 2*n+2, level ? `First digit 1: ${n} codes. First digit not 1 but last digit 1: ${n-1}. Total ${2*n-1}.` : `The color cases are disjoint: ${n} + ${n+2} = ${2*n+2}.`);
      case 'brain-symmetry': return numeric(level ? `Uniformly shuffle ${n+2} distinct cards. What is the probability that card A appears before card B? Enter a decimal.` : `Uniformly shuffle ${n+2} distinct cards. What is the probability that card A is first?`,level ? .5 : 1/(n+2),level ? 'Exchanging A and B pairs every A-before-B ordering with exactly one B-before-A ordering. Probability = 1/2.' : `All ${n+2} cards have the same chance of being first: 1/${n+2}.`);
      case 'brain-bounds': return numeric(level ? `${n*4+1} tasks must be assigned to ${n} workers. What is the smallest achievable maximum number of tasks assigned to any one worker? Tasks are indivisible.` : `${n*4+1} people need seats at tables holding at most 4 people. What is the minimum number of tables?`,level ? 5 : n+1,level ? 'If everyone had at most 4 tasks, capacity would be too small. Give one worker 5 and the rest 4; the bound is attained.' : `At least ceil(${n*4+1}/4) = ${n+1}. Fill ${n} tables and seat the last person at another.`);
      case 'brain-conditioning': return numeric(level ? `Pick bag A with probability 1/4, otherwise bag B. A always pays ${n*4}; B pays ${n*2}. What is the expected payoff?` : `Pick bag A or B with equal probability. A always pays ${n}; B pays ${n*3}. What is the expected payoff?`,level ? n*2.5 : n*2,level ? `0.25 × ${n*4} + 0.75 × ${n*2} = ${n*2.5}.` : `0.5 × ${n} + 0.5 × ${n*3} = ${n*2}.`);
      case 'prob-independent': return numeric(level ? `An independent trial succeeds with probability 1/2. What is the probability of at least one success in ${seed%3+2} trials?` : `Two independent events have probabilities 1/2 and ${n}/20. What is the probability that both occur?`,level ? 1-.5**(seed%3+2) : n/40,level ? `Use the complement of all failures: 1 - (1/2)^${seed%3+2}.` : `(1/2) × (${n}/20) = ${n}/40.`);
      case 'prob-bayes': return numeric(level ? `A condition affects 10 of 100 people. A test flags 8 of those 10 and 9 of the other 90. What is P(condition | flagged)?` : `${n} true events and ${n+2} false alarms produce a signal. Given a signal, what is the probability of a true event?`,level ? 8/17 : n/(2*n+2),level ? 'There are 8 true positives and 9 false positives: 8/(8+9) = 8/17.' : `${n}/(${n}+${n+2}). Condition on all signals.`);
      case 'prob-variance': return numeric(level ? `A random value has variance ${n}. Add 7 to every outcome. What is its new variance?` : `An equal chance of ${n-2} or ${n+2} has what variance?`,level ? n : 4,level ? 'Adding a constant shifts outcomes and mean equally. Deviations, and therefore variance, do not change.' : `The mean is ${n}; each squared deviation is 4.`);
      case 'arith-percent': return numeric(`What is ${n * 5}% of ${40 + n * 10}?`, n*5*(40+n*10)/100, `(${n*5} / 100) × ${40+n*10} = ${n*5*(40+n*10)/100}.`);
      case 'arith-fraction': return numeric(`Express ${n} / 20 as a percentage. Enter the number without %.`, n*5, `${n} / 20 × 100 = ${n*5}%.`);
      case 'arith-return': return numeric(`A portfolio starts at 100, rises ${n}%, then falls ${n}%. What is its final value?`, (10000-n*n)/100, `100 × (1 + ${n}/100) × (1 - ${n}/100) = ${(10000-n*n)/100}.`);
      case 'prob-complement': return numeric(`Failure probability is ${n}/20. What is success probability? Enter a decimal or fraction.`, 1-n/20, `1 - ${n}/20 = ${(20-n)/20}.`);
      case 'prob-conditional': return numeric(`Of ${n*4} days when a signal fired, ${n+3} had a positive return. What fraction of signal days had a positive return?`, (n+3)/(n*4), `${n+3} / ${n*4}. The denominator includes only signal days.`);
      case 'prob-ev': return numeric(`A fair coin game pays ${n*3} on heads and loses ${n} on tails. What is expected net payoff?`,n, `0.5 × ${n*3} + 0.5 × (-${n}) = ${n}.`);
      case 'brain-pigeon': return numeric(`A drawer has unlimited socks in ${n} colors. Drawing without looking, how many socks guarantee two of the same color?`,n+1, `The first ${n} can have distinct colors. Draw ${n+1} must repeat a color.`);
      case 'brain-balance': { const k=seed%3+2, coins=3**k; q.id = `${id}:${k}`; return numeric(`Among ${coins} identical-looking coins, exactly one is heavier. Using a balance scale, what is the minimum number of weighings needed in the worst case?`,k, `Each weighing has three outcomes. ${k} balanced ternary splits distinguish ${coins} candidates; fewer cannot.`); }
      case 'brain-invariant': return numeric(`There are ${2*n+1} tokens. You may only remove exactly two at a time. What is the smallest number of tokens that can remain?`,1, 'Subtracting two preserves odd parity. Repeated removal reaches 1, never 0.');
    }
    const code = (name,args,prompt,tests,solution) => Object.assign(q,{kind:'code',functionName:name,starterCode:`def ${name}(${args}):\n    pass\n`,prompt,testCases:tests.map(([input,expected])=>({input,expected:String(expected), tolerance:0.000001})),solution,topic:id});
    if(level) {
      switch(id) {
        case 'code-pnl': return code('break_even_exit','quantity, entry_price, target_pnl','Return the exit price needed for target_pnl. Quantity is nonzero and signed. Round to 6 decimals.', [[`2, 100, ${n*2}`,100+n],['-2, 100, 10',95],['5, 20, 0',20]],'return round(entry_price + target_pnl / quantity, 6)');
        case 'code-ev': return code('net_value','outcomes, probabilities, fee','Return expected net payoff after paying a fixed entry fee, rounded to 6 decimals.',[[`[${n}, ${n+4}], [0.5, 0.5], 2`,n],['[-4, 8], [0.75, 0.25], 1',-2],['[5], [1], 5',0]],'return round(sum(x * p for x, p in zip(outcomes, probabilities)) - fee, 6)');
        case 'code-variance': return code('shifted_variance','values, shift','Add shift to every value, then return population variance rounded to 6 decimals. Can you avoid allocating a new list?',[[`[${n}, ${n+2}], 100`,1],['[5, 5, 5], -8',0],['[-2, 0, 2], 9',2.666667]],'mean = sum(values) / len(values)\nreturn round(sum((x - mean) ** 2 for x in values) / len(values), 6)');
        case 'code-call': return code('call_spread_profit','spot, low_strike, high_strike, net_premium','Return expiry profit of a long call at low_strike and a short call at high_strike, after subtracting net premium. low_strike < high_strike.',[[`${100+n}, 100, 110, 3`,Math.min(n,10)-3],['90, 100, 110, 3',-3],['105, 100, 110, 3',2]],'return max(spot - low_strike, 0) - max(spot - high_strike, 0) - net_premium');
        case 'code-simulation': return code('estimate_both','draws, threshold','Each draw is a pair of simulated values. Return the fraction where BOTH are below threshold, rounded to 6 decimals. Draws is nonempty.',[[`[(${n/20}, 0.2), (0.8, 0.1)], 0.5`,n<10?.5:0],['[(0.5, 0.1)], 0.5',0],['[(0.1, 0.5)], 0.5',0],['[(0.1, 0.8)], 0.5',0],['[(0.8, 0.1)], 0.5',0],['[(0.1, 0.1)], 0.5',1]],'return round(sum(a < threshold and b < threshold for a, b in draws) / len(draws), 6)');
      }
    }
    switch(id) {
      case 'code-simulation': return code('estimate_probability','draws, threshold','Return the fraction of supplied simulated draws strictly below threshold. Round to 6 decimals. Draws is nonempty.',[[`[${n/20}, 0.6, 0.8, 0.3], 0.5`,n<10?.5:.25],['[0.5], 0.5',0],['[0.1, 0.2, 0.3], 0.5',1]],'return round(sum(x < threshold for x in draws) / len(draws), 6)');
      case 'code-pnl': return code('pnl','quantity, entry_price, exit_price','Write pnl(quantity, entry_price, exit_price). Return signed position profit. Inputs are integers.', [[`${n}, 100, 103`,n*3],[`${-n}, 100, 103`,-n*3],['0, 50, 70',0],[`${n}, 103, 100`,-n*3]],'return quantity * (exit_price - entry_price)');
      case 'code-ev': return code('expected_value','outcomes, probabilities','Return the weighted expected value, rounded to 6 decimal places. Inputs are equal-length nonempty lists; probabilities sum to 1.',[[`[${n}, ${n+4}], [0.5, 0.5]`,n+2],['[-4, 8], [0.75, 0.25]',-1],['[5], [1]',5]],'return round(sum(x * p for x, p in zip(outcomes, probabilities)), 6)');
      case 'code-variance': return code('variance','values','Return the population variance of a nonempty list, rounded to 6 decimal places.',[[`[${n}, ${n+2}]`,1],['[5, 5, 5]',0],['[-2, 0, 2]',2.666667]],'mean = sum(values) / len(values)\nreturn round(sum((x - mean) ** 2 for x in values) / len(values), 6)');
      case 'code-call': return code('call_profit','spot, strike, premium','Return the expiry profit of one long call per unit, subtracting its premium. Inputs are integers.',[[`${100+n}, 100, 3`,n-3],['90, 100, 4',-4],['100, 100, 4',-4]],'return max(spot - strike, 0) - premium');
    }
  }
  const order=['arith-percent','arith-fraction','arith-return','prob-complement','prob-conditional','prob-independent','prob-bayes','prob-ev','prob-variance','brain-cases','brain-pigeon','brain-balance','brain-invariant','brain-symmetry','brain-bounds','brain-conditioning','code-pnl','code-ev','code-simulation','code-variance','code-call'];
  skills.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));
  const objectives={
    'arith-percent':'Calculate and invert a percentage of a stated base.', 'arith-fraction':'Translate among fractions, percentages and part-to-whole ratios.', 'arith-return':'Compound growth factors and solve a recovery-return problem.',
    'prob-complement':'Use an exhaustive partition without confusing disjoint and independent events.', 'prob-conditional':'Construct the conditioned sample space and its denominator.', 'prob-independent':'Multiply only under independence and use complements for repeated trials.', 'prob-bayes':'Include base rates and false positives when reversing a condition.', 'prob-ev':'Compute expected net payoff and derive a fair entry fee.', 'prob-variance':'Compute dispersion and explain translation invariance.',
    'brain-cases':'Count disjoint exhaustive cases without double counting.', 'brain-pigeon':'Construct a worst case and identify the first guaranteed repetition.', 'brain-balance':'Connect an information lower bound with a balanced construction.', 'brain-invariant':'Identify a preserved residue to rule out an unreachable state.', 'brain-symmetry':'Justify equal probabilities by a relabeling bijection.', 'brain-bounds':'Prove a lower bound and provide an attaining allocation.', 'brain-conditioning':'Combine first-step branches with their correct weights.',
    'code-pnl':'Implement signed P&L and rearrange it to solve for an exit price.', 'code-ev':'Aggregate weighted outcomes and subtract a fixed fee.', 'code-simulation':'Estimate single and joint events from reproducible simulated draws.', 'code-variance':'Implement population variance and exploit shift invariance.', 'code-call':'Separate expiry payoff from profit and compose a call spread.'
  };
  const errors={
    'arith-percent':'Using the final amount as the original percentage base.', 'arith-fraction':'Confusing a part-to-part ratio with a part-to-whole fraction.', 'arith-return':'Adding percentage changes that use different bases.',
    'prob-complement':'Subtracting from 100 when the answer is expressed as a probability.', 'prob-conditional':'Keeping the unconditional denominator.', 'prob-independent':'Multiplying dependent events without a condition.', 'prob-bayes':'Ignoring false positives or base rates.', 'prob-ev':'Treating expected value as a guaranteed outcome or forgetting the entry cost.', 'prob-variance':'Confusing a change in mean with a change in dispersion.',
    'brain-cases':'Counting the overlap twice.', 'brain-pigeon':'Giving a possible result instead of a worst-case guarantee.', 'brain-balance':'Stating a bound without an achievable comparison strategy.', 'brain-invariant':'Tracking examples without identifying what the operation preserves.', 'brain-symmetry':'Assuming symmetry when sampling is not uniform.', 'brain-bounds':'Giving a lower bound without an attaining construction.', 'brain-conditioning':'Averaging branches without their probabilities.',
    'code-pnl':'Losing the sign of a short position.', 'code-ev':'Pairing weights with the wrong outcomes.', 'code-simulation':'Using a strict threshold as an inclusive threshold or confusing a sample estimate with an exact probability.', 'code-variance':'Dividing by n - 1 when population variance is requested.', 'code-call':'Confusing payoff with profit or forgetting the short leg.'
  };
  for(const s of skills) {s.objective=objectives[s.id];s.commonError=errors[s.id];s.contentVersion=1;}
  const reasons={
    'brain-cases':['cases','Partition into disjoint cases and add their counts.','Multiply the counts of overlapping cases.'],
    'brain-pigeon':['worst','Fill every category to one below the target, then add one.','The most likely arrangement determines a guarantee.'],
    'brain-balance':['tree','Three outcomes per weighing give a bound; equal groups attain it.','Two pans mean exactly two outcomes per weighing.'],
    'brain-invariant':['residue','Removing a fixed amount preserves the remainder modulo that amount.','Every smaller nonnegative count must eventually be reachable.'],
    'brain-symmetry':['bijection','A label swap pairs equally likely outcomes without changing the experiment.','All named events have equal probability even without a symmetry.'],
    'brain-bounds':['construct','Capacity gives a lower bound, and an explicit allocation attains it.','A lower bound alone always proves the optimum is achievable.'],
    'brain-conditioning':['branches','Weight each first-step branch by its probability, then add.','Average all branch values equally regardless of their probabilities.']
  };
  const transferHints={
    'arith-percent':['The new price is 120% of the original.', 'Divide the final price by 1.2; do not take 20% off the final price.'],
    'arith-fraction':['The ratio has five parts in total.', 'Cash is two of those five parts, not two thirds of the total.'],
    'arith-return':['Use the reduced value as the base for the recovery gain.', 'A fall from 100 to 80 needs a gain of 20/80.'],
    'prob-complement':['The stated outcomes are mutually exclusive and exhaustive.', 'Subtract both known probabilities from 1.'],
    'prob-conditional':['List only the even die outcomes.', 'Within {2,4,6}, count the outcomes exceeding 3.'],
    'prob-ev':['Net value equals gross expected payoff minus the entry fee.', 'A fair fee equals the probability-weighted gross payoff.'],
    'prob-independent':['At least one success is the complement of all failures.', 'Independence lets you multiply the failure probabilities.'],
    'prob-bayes':['Of the flagged cases, 8 are true and 9 are false.', 'Use all flagged cases, not all people, in the denominator.'],
    'prob-variance':['Adding a constant shifts the mean by the same constant.', 'The deviations from the mean do not change.'],
    'brain-pigeon':['Avoid a triple by drawing two socks of every color.', 'That worst case has twice the number of colors. One more draw forces a triple.'],
    'brain-balance':['Build a decision tree with three outcomes at every level.', 'Equal three-way partitions attain 3 raised to the number of weighings.'],
    'brain-invariant':['Subtracting 3 preserves the remainder modulo 3, not parity.', 'Write the initial count as a multiple of 3 plus a remainder.'],
    'brain-cases':['Separate first digit 1 from first digit not 1.', 'In the second case, only last digit 1 qualifies. These cases do not overlap.'],
    'brain-symmetry':['Swap A and B in each ordering.', 'The swap pairs every A-before-B outcome with a B-before-A outcome.'],
    'brain-bounds':['Could all workers have at most four tasks?', 'Capacity would be one short. Assign five to one worker and four to each other worker.'],
    'brain-conditioning':['The first branch has weight 1/4; the other has weight 3/4.', 'Multiply each payoff by its own weight, then add.'],
    'code-pnl':['Rearrange target_pnl = quantity * (exit_price - entry_price).', 'Divide the target by the signed quantity and add entry_price.'],
    'code-ev':['Compute expected gross payoff first.', 'Subtract the fixed fee once, outside the weighted sum.'],
    'code-variance':['A common shift changes the mean but not deviations.', 'Compute the variance of the original values, avoiding another list.'],
    'code-call':['The short call subtracts the high-strike payoff.', 'Subtract the net premium once after combining the long and short payoffs.'],
    'code-simulation':['Both coordinates must be strictly below the threshold.', 'Use a < threshold and b < threshold; equality must fail for either coordinate.']
  };
  function question(id,seed,harder=false,level=0) {
    const q=buildQuestion(id,seed,harder,level);q.familyId=`${id}:${level?'transfer':'foundation'}`;
    if(level) q.hints=transferHints[id] || q.hints;
    if(reasons[id]) {const [value,good,bad]=reasons[id];q.correctReason=value;
      q.reasonOptions=[{value,label:good},{value:'unsupported',label:bad}];
      if(seed%2)q.reasonOptions.reverse();
    }
    const n=(seed%9)+2+(harder?5:0), k=seed%3+2;
    const checks={
      'brain-pigeon':{prompt:'How many socks can the worst case contain before the guarantee is forced?',answer:level?2*n:n},
      'brain-balance':{prompt:level?'In the first weighing, how many candidate positions belong in each of the three equal branches?':'How many coins belong in EACH of the three equal groups at the first split?',answer:3**(k-1)},
      'brain-invariant':{prompt:'Which modulus is preserved by the allowed removal? Enter that modulus.',answer:level?3:2},
      'brain-bounds':{prompt:level?'To attain the bound, how many workers get five tasks when every other worker gets four?':'To attain the bound, how many tables are completely full (with one person at the last table)?',answer:level?1:n}
    };
    if(checks[id]) q.construction=checks[id];
    if(level && id==='brain-invariant') {q.explanation='Removing a fixed k preserves the remainder modulo k. The relevant invariant depends on the operation; subtracting 3 does not preserve parity.';q.workedExample='Starting with 14 and removing 4 at a time leaves a minimum of 2, because 14 = 3 × 4 + 2.';}
    if(level && id==='brain-pigeon') {q.explanation='To force t objects in one category, first count the worst arrangement with at most t - 1 in every category, then add one.';q.workedExample='With 4 colors, eight socks can have two of each. Nine guarantee three of a color.';}
    if(level && id==='arith-percent') {q.explanation='Invert percentage growth by dividing by the growth factor. Subtracting the same percentage from the final amount uses the wrong base.';q.workedExample='A 25% rise produces 150. Original value = 150 / 1.25 = 120.';}
    // Content identity is independent of generation IDs, seeds and presentation order.
    q.semanticKey=JSON.stringify([1,q.skillId,q.familyId,q.prompt,q.functionName || null,q.testCases || null,q.answer ?? null,q.solution,q.construction || null]);
    return q;
  }
  return {skills,get,question};
})();
if (typeof module !== 'undefined') module.exports = QuantCurriculum;
